version: "3.9"

services:
  backend:
    build:
      context: ./backend
    container_name: trading_backend
    ports:
      - "8000:8000"
    env_file:
      - ./backend/.env.prod
    depends_on:
      - db

  frontend:
    build:
      context: ./frontend
    container_name: trading_frontend
    ports:
      - "5173:80"
    depends_on:
      - backend

  db:
    image: postgres:16
    container_name: trading_db
    restart: always
    environment:
      POSTGRES_USER: trading_user
      POSTGRES_PASSWORD: trade
      POSTGRES_DB: trading_platform
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
